# PANGPANGDigital è‡ªç”¨ Mihomo Rule-set é…ç½®æ–‡ä»¶
# æœ€åæ›´æ–°æ—¶é—´ï¼š2025-12-21 12:50
# url é‡Œå¡«å†™è‡ªå·±çš„è®¢é˜…,åç§°ä¸èƒ½é‡å¤
proxy-providers:
  provider1:
    url: "å¡«å†™è®¢é˜…é“¾æ¥"
    type: http
    interval: 86400
    health-check: {enable: true,url: "https://www.gstatic.com/generate_204",interval: 300}
    override:
      additional-prefix: "[å¡«å†™æœºåœºåå­—]"

  provider2:
    url: "å¡«å†™è®¢é˜…é“¾æ¥"
    type: http
    interval: 86400
    health-check: {enable: true,url: "https://www.gstatic.com/generate_204",interval: 300}
    override:
      additional-prefix: "[å¡«å†™æœºåœºåå­—]"


mixed-port: 7890
ipv6: true
allow-lan: true
unified-delay: false
tcp-concurrent: true
external-controller: 127.0.0.1:9090
external-ui: ui
external-ui-url: "https://github.com/MetaCubeX/metacubexd/archive/refs/heads/gh-pages.zip"

find-process-mode: strict
global-client-fingerprint: chrome

profile:
  store-selected: true
  store-fake-ip: true

sniffer:
  enable: true
  sniff:
    HTTP:
      ports: [80, 8080-8880]
      override-destination: true
    TLS:
      ports: [443, 8443]
    QUIC:
      ports: [443, 8443]
  skip-domain:
    - "Mijia Cloud"
    - "+.push.apple.com"

tun:
  enable: true
  stack: mixed
  dns-hijack:
    - "any:53"
    - "tcp://any:53"
  auto-route: true
  auto-redirect: true
  auto-detect-interface: true

dns:
  enable: true
  ipv6: true
  enhanced-mode: fake-ip
  fake-ip-filter:
    - "*"
    - "+.lan"
    - "+.local"
    - "+.market.xiaomi.com"
  default-nameserver:
    - tls://223.5.5.5
    - tls://223.6.6.6
  nameserver:
    - https://doh.pub/dns-query
    - https://dns.alidns.com/dns-query

proxy-groups:

  - name: å›½å¤–æµé‡
    type: select
    icon: https://raw.githubusercontent.com/PANGPANGDigital/GoodGoodStudyDayDayUp/main/Surge/icon/images/Tesla.png
    proxies: [è‡ªå»ºèŠ‚ç‚¹,é¦™æ¸¯èŠ‚ç‚¹,å°æ¹¾èŠ‚ç‚¹,æ—¥æœ¬èŠ‚ç‚¹,æ–°åŠ å¡èŠ‚ç‚¹,ç¾å›½èŠ‚ç‚¹,å…¶å®ƒåœ°åŒº]

  - name: YouTube
    type: select
    icon: https://raw.githubusercontent.com/lige47/QuanX-icon-rule/main/icon/04ProxySoft/youtube(4).png
    proxies: [å›½å¤–æµé‡,é¦™æ¸¯èŠ‚ç‚¹,å°æ¹¾èŠ‚ç‚¹,æ—¥æœ¬èŠ‚ç‚¹,æ–°åŠ å¡èŠ‚ç‚¹,ç¾å›½èŠ‚ç‚¹,å…¶å®ƒåœ°åŒº]

  - name: Paypal
    type: select
    icon: https://raw.githubusercontent.com/lige47/QuanX-icon-rule/main/icon/04ProxySoft/paypal(2).png
    proxies: [å›½å¤–æµé‡,ç¾å›½èŠ‚ç‚¹]

  - name: OpenAI
    type: select
    icon: https://raw.githubusercontent.com/lige47/QuanX-icon-rule/main/icon/04ProxySoft/ChatGPT-green.png
    proxies: [å›½å¤–æµé‡,é¦™æ¸¯èŠ‚ç‚¹,å°æ¹¾èŠ‚ç‚¹,æ—¥æœ¬èŠ‚ç‚¹,æ–°åŠ å¡èŠ‚ç‚¹,ç¾å›½èŠ‚ç‚¹,å…¶å®ƒåœ°åŒº]

  - name: Telegram
    type: select
    icon: https://raw.githubusercontent.com/lige47/QuanX-icon-rule/main/icon/04ProxySoft/Telegrampremium.png
    proxies: [å›½å¤–æµé‡,é¦™æ¸¯èŠ‚ç‚¹,å°æ¹¾èŠ‚ç‚¹,æ—¥æœ¬èŠ‚ç‚¹,æ–°åŠ å¡èŠ‚ç‚¹,ç¾å›½èŠ‚ç‚¹,å…¶å®ƒåœ°åŒº]

  - name: Microsoft
    type: select
    icon: https://raw.githubusercontent.com/lige47/QuanX-icon-rule/main/icon/03CNSoft/microsoft.png
    proxies: [DIRECT,å›½å¤–æµé‡,é¦™æ¸¯èŠ‚ç‚¹,å°æ¹¾èŠ‚ç‚¹,æ—¥æœ¬èŠ‚ç‚¹,æ–°åŠ å¡èŠ‚ç‚¹,ç¾å›½èŠ‚ç‚¹,å…¶å®ƒåœ°åŒº]

  - name: Adobe
    type: select
    icon: https://raw.githubusercontent.com/lige47/QuanX-icon-rule/main/icon/04ProxySoft/Adobe(1).png
    proxies:  [REJECT,å›½å¤–æµé‡,é¦™æ¸¯èŠ‚ç‚¹,å°æ¹¾èŠ‚ç‚¹,æ—¥æœ¬èŠ‚ç‚¹,æ–°åŠ å¡èŠ‚ç‚¹,ç¾å›½èŠ‚ç‚¹,å…¶å®ƒåœ°åŒº]

  - name: Apple
    type: select
    icon: https://raw.githubusercontent.com/lige47/QuanX-icon-rule/main/icon/03CNSoft/apple.png
    proxies:  [DIRECT,å›½å¤–æµé‡,é¦™æ¸¯èŠ‚ç‚¹,å°æ¹¾èŠ‚ç‚¹,æ—¥æœ¬èŠ‚ç‚¹,æ–°åŠ å¡èŠ‚ç‚¹,ç¾å›½èŠ‚ç‚¹,å…¶å®ƒåœ°åŒº]

  - name: Steam
    type: select
    icon: https://raw.githubusercontent.com/lige47/QuanX-icon-rule/main/icon/03CNSoft/steam(1).png
    proxies:  [DIRECT,å›½å¤–æµé‡,é¦™æ¸¯èŠ‚ç‚¹,å°æ¹¾èŠ‚ç‚¹,æ—¥æœ¬èŠ‚ç‚¹,æ–°åŠ å¡èŠ‚ç‚¹,ç¾å›½èŠ‚ç‚¹,å…¶å®ƒåœ°åŒº]

  - name: å›½å†…æµé‡
    type: select
    icon: https://raw.githubusercontent.com/lige47/QuanX-icon-rule/main/icon/01Country/chinese.png
    proxies:  [DIRECT]

  - name: Final
    type: select
    icon: https://raw.githubusercontent.com/PANGPANGDigital/GoodGoodStudyDayDayUp/main/Surge/icon/images/Fries.png
    proxies:  [DIRECT,å›½å¤–æµé‡,é¦™æ¸¯èŠ‚ç‚¹,å°æ¹¾èŠ‚ç‚¹,æ—¥æœ¬èŠ‚ç‚¹,æ–°åŠ å¡èŠ‚ç‚¹,ç¾å›½èŠ‚ç‚¹,å…¶å®ƒåœ°åŒº]

  #åˆ†éš”,ä¸‹é¢æ˜¯åœ°åŒºåˆ†ç»„
  - name: è‡ªå»ºèŠ‚ç‚¹
    type: select
    icon: https://raw.githubusercontent.com/PANGPANGDigital/GoodGoodStudyDayDayUp/main/Surge/icon/images/Sub.png
    include-all: true
    exclude-type: direct
    filter: "(?i)DMIT"

  - name: é¦™æ¸¯èŠ‚ç‚¹
    type: fallback
    icon: https://raw.githubusercontent.com/PANGPANGDigital/GoodGoodStudyDayDayUp/main/Surge/icon/images/HK.png
    include-all: true
    exclude-type: direct
    filter: "(?i)æ¸¯|hk|hongkong|hong kong"
    url: https://www.gstatic.com/generate_204
    interval: 300

  - name: å°æ¹¾èŠ‚ç‚¹
    type: fallback
    icon: https://raw.githubusercontent.com/PANGPANGDigital/GoodGoodStudyDayDayUp/main/Surge/icon/images/TW.png
    include-all: true
    exclude-type: direct
    filter: "(?i)å°|tw|taiwan"
    url: https://www.gstatic.com/generate_204
    interval: 300

  - name: æ—¥æœ¬èŠ‚ç‚¹
    type: fallback
    icon: https://raw.githubusercontent.com/PANGPANGDigital/GoodGoodStudyDayDayUp/main/Surge/icon/images/JP.png
    include-all: true
    exclude-type: direct
    filter: "(?i)æ—¥|jp|japan"
    url: https://www.gstatic.com/generate_204
    interval: 300

  - name: ç¾å›½èŠ‚ç‚¹
    type: fallback
    icon: https://raw.githubusercontent.com/PANGPANGDigital/GoodGoodStudyDayDayUp/main/Surge/icon/images/US.png
    include-all: true
    exclude-type: direct
    filter: "(?i)ç¾|us|unitedstates|united states"
    url: https://www.gstatic.com/generate_204
    interval: 300

  - name: æ–°åŠ å¡èŠ‚ç‚¹
    type: fallback
    icon: https://raw.githubusercontent.com/PANGPANGDigital/GoodGoodStudyDayDayUp/main/Surge/icon/images/SG.png
    include-all: true
    exclude-type: direct
    filter: "(?i)(æ–°|sg|singapore)"
    url: https://www.gstatic.com/generate_204
    interval: 300
    
  - name: å…¶å®ƒåœ°åŒº
    type: select
    icon: https://raw.githubusercontent.com/PANGPANGDigital/GoodGoodStudyDayDayUp/main/Surge/icon/images/UN.png
    include-all: true
    exclude-type: direct
    filter: "(?i)^(?!.*(?:ğŸ‡­ğŸ‡°|ğŸ‡¯ğŸ‡µ|ğŸ‡ºğŸ‡¸|ğŸ‡¸ğŸ‡¬|ğŸ‡¨ğŸ‡³|æ¸¯|hk|hongkong|å°|tw|taiwan|æ—¥|jp|japan|æ–°|sg|singapore|ç¾|us|unitedstates)).*"



rules:
  - RULE-SET,private_ip,DIRECT,no-resolve
  - RULE-SET,youtube_domain,YouTube
  - RULE-SET,paypal_domain,Paypal
  - RULE-SET,openai_domain,OpenAI
  - RULE-SET,telegram_domain,Telegram
  - RULE-SET,microsoft_domain,Microsoft
  - RULE-SET,adobe_domain,Adobe
  - RULE-SET,apple_domain,Apple
  - RULE-SET,steam_domain,Steam
  - RULE-SET,cn_domain,å›½å†…æµé‡
  - RULE-SET,geolocation-!cn,å›½å¤–æµé‡

  - RULE-SET,telegram_ip,Telegram
  - RULE-SET,cn_ip,å›½å†…æµé‡
  - MATCH,Final

rule-anchor:
  ip: &ip {type: http, interval: 86400, behavior: ipcidr, format: mrs}
  domain: &domain {type: http, interval: 86400, behavior: domain, format: mrs}
rule-providers:
  private_domain:
    <<: *domain
    url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/private.mrs"
  cn_domain:
    <<: *domain
    url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/cn.mrs"
  youtube_domain:
    <<: *domain
    url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/youtube.mrs"
  paypal_domain:
    <<: *domain
    url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/paypal.mrs"
  openai_domain:
    <<: *domain
    url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/openai.mrs"
  telegram_domain:
    <<: *domain
    url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/telegram.mrs"  
  microsoft_domain:
    <<: *domain
    url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/microsoft.mrs"
  adobe_domain:
    <<: *domain
    url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/adobe.mrs"
  apple_domain:
    <<: *domain
    url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/apple.mrs"
  steam_domain:
    <<: *domain
    url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/steam.mrs"
  geolocation-!cn:
    <<: *domain
    url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/geolocation-!cn.mrs"

  private_ip:
    <<: *ip
    url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/private.mrs"
  cn_ip:
    <<: *ip
    url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/cn.mrs"
  telegram_ip:
    <<: *ip
    url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/telegram.mrs"
